name: release
on:
  push:
    branches:
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v2
      - run: npm install
      - run: node_modules/.bin/gulp pug
      - run: node_modules/.bin/sass -s compressed scss/bootstrap.scss static/style.css
      - run: cp static/* dist/
      - run: firebase deploy --only hosting:release --token ${{ secrets.FIREBASE_TOKEN }}
