name: staging
on:
  push:
    branches:
      - staging
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v2
      - run: npm install
      - run: node_modules/.bin/gulp pug
      - run: node_modules/.bin/sass -s compressed scss/bootstrap.scss static/style.css
      - run: cp static/* dist/
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:staging
